documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "README.md"

source:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

build:
  - changed-files:
      - any-glob-to-any-file:
          - "*.props"
          - "*.targets"
          - "*.csproj"
          - "global.json"
          - "version.json"
          - ".github/workflows/**"
