name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
include-pre-releases: false
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "breaking"
      - "major"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "fix"
      - "documentation"
  default: patch
categories:
  - title: "Breaking changes"
    labels:
      - "breaking"
      - "major"
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "Maintenance"
    label: "chore"
exclude-labels:
  - "skip-changelog"
  - "dependencies"
